In [2]:
import os
import numpy as np
import pandas as pd
import pickle
import warnings

In [3]:
file_path='./data/traffic/period-7.csv'
raw_data_path = os.path.join(os.path.dirname(file_path), "raw_data.pickle")

In [6]:
tem = pd.read_csv(file_path)

In [7]:
tem

,deliveryPeriodIndex,advertiserNumber,advertiserCategoryIndex,budget,CPAConstraint,timeStepIndex,remainingBudget,pvIndex,pValue,pValueSigma,bid,xi,adSlot,cost,isExposed,conversionAction,leastWinningCost,isEnd
0,7.0,0.0,0.0,750.0,8.0,0.0,750.000000,0.0,0.005964,0.0,0.089458,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
1,7.0,1.0,0.0,1350.0,7.0,0.0,1350.000000,0.0,0.006934,0.0,0.006934,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
2,7.0,2.0,0.0,2250.0,7.0,0.0,2250.000000,0.0,0.003792,0.0,0.003792,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
3,7.0,3.0,0.0,900.0,10.0,0.0,900.000000,0.0,0.001558,0.0,0.008804,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
4,7.0,4.0,0.0,750.0,9.0,0.0,750.000000,0.0,0.006401,0.0,0.056443,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23998843,7.0,43.0,5.0,2400.0,9.0,47.0,1933.500176,6477.0,0.004280,0.0,0.038522,0.0,0.0,0.0,0.0,0.0,0.067568,0.0
23998844,7.0,44.0,5.0,5400.0,7.0,47.0,2285.252223,6477.0,0.005072,0.0,0.035507,0.0,0.0,0.0,0.0,0.0,0.067568,0.0
23998845,7.0,45.0,5.0,2100.0,9.0,47.0,0.035007,6477.0,0.003566,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.067568,1.0
23998846,7.0,46.0,5.0,5550.0,8.0,47.0,3959.654407,6477.0,0.004498,0.0,0.041452,0.0,0.0,0.0,0.0,0.0,0.067568,0.0
23998847,7.0,47.0,5.0,450.0,12.0,47.0,10.021143,6477.0,0.000136,0.0,0.000982,0.0,0.0,0.0,0.0,0.0,0.067568,0.0

In [9]:
tem[tem.advertiserNumber==0]

,deliveryPeriodIndex,advertiserNumber,advertiserCategoryIndex,budget,CPAConstraint,timeStepIndex,remainingBudget,pvIndex,pValue,pValueSigma,bid,xi,adSlot,cost,isExposed,conversionAction,leastWinningCost,isEnd
0,7.0,0.0,0.0,750.0,8.0,0.0,750.000000,0.0,0.005964,0.0,0.089458,0.0,0.0,0.000000,0.0,0.0,0.110844,0.0
48,7.0,0.0,0.0,750.0,8.0,0.0,750.000000,1.0,0.003294,0.0,0.049403,0.0,0.0,0.000000,0.0,0.0,0.112206,0.0
96,7.0,0.0,0.0,750.0,8.0,0.0,750.000000,2.0,0.000595,0.0,0.008929,0.0,0.0,0.000000,0.0,0.0,0.123952,0.0
144,7.0,0.0,0.0,750.0,8.0,0.0,750.000000,3.0,0.003358,0.0,0.050363,0.0,0.0,0.000000,0.0,0.0,0.117005,0.0
192,7.0,0.0,0.0,750.0,8.0,0.0,750.000000,4.0,0.009974,0.0,0.149612,1.0,2.0,0.147006,1.0,0.0,0.142466,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23998608,7.0,0.0,0.0,750.0,8.0,47.0,0.002493,6473.0,0.011383,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.098122,1.0
23998656,7.0,0.0,0.0,750.0,8.0,47.0,0.002493,6474.0,0.005185,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.043405,1.0
23998704,7.0,0.0,0.0,750.0,8.0,47.0,0.002493,6475.0,0.009298,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.102183,1.0
23998752,7.0,0.0,0.0,750.0,8.0,47.0,0.002493,6476.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.115953,1.0
23998800,7.0,0.0,0.0,750.0,8.0,47.0,0.002493,6477.0,0.012338,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.067568,1.0

In [18]:
tem[tem.timeStepIndex==0]

,deliveryPeriodIndex,advertiserNumber,advertiserCategoryIndex,budget,CPAConstraint,timeStepIndex,remainingBudget,pvIndex,pValue,pValueSigma,bid,xi,adSlot,cost,isExposed,conversionAction,leastWinningCost,isEnd
0,7.0,0.0,0.0,750.0,8.0,0.0,750.0,0.0,0.005964,0.0,0.089458,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
1,7.0,1.0,0.0,1350.0,7.0,0.0,1350.0,0.0,0.006934,0.0,0.006934,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
2,7.0,2.0,0.0,2250.0,7.0,0.0,2250.0,0.0,0.003792,0.0,0.003792,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
3,7.0,3.0,0.0,900.0,10.0,0.0,900.0,0.0,0.001558,0.0,0.008804,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
4,7.0,4.0,0.0,750.0,9.0,0.0,750.0,0.0,0.006401,0.0,0.056443,0.0,0.0,0.0,0.0,0.0,0.110844,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600763,7.0,43.0,5.0,2400.0,9.0,0.0,2400.0,12515.0,0.005556,0.0,0.036590,0.0,0.0,0.0,0.0,0.0,0.126408,0.0
600764,7.0,44.0,5.0,5400.0,7.0,0.0,5400.0,12515.0,0.004791,0.0,0.050310,0.0,0.0,0.0,0.0,0.0,0.126408,0.0
600765,7.0,45.0,5.0,2100.0,9.0,0.0,2100.0,12515.0,0.000696,0.0,0.013840,0.0,0.0,0.0,0.0,0.0,0.126408,0.0
600766,7.0,46.0,5.0,5550.0,8.0,0.0,5550.0,12515.0,0.007907,0.0,0.072322,0.0,0.0,0.0,0.0,0.0,0.126408,0.0
600767,7.0,47.0,5.0,450.0,12.0,0.0,450.0,12515.0,0.010217,0.0,0.113745,0.0,0.0,0.0,0.0,0.0,0.126408,0.0

In [17]:
tem.pvIndex.value_counts()

0.0        2304
900.0      2304
898.0      2304
897.0      2304
896.0      2304
           ...
24803.0      48
24804.0      48
24805.0      48
24806.0      48
26545.0      48
Name: pvIndex, Length: 26546, dtype: int64

In [19]:
tem.advertiserNumber.value_counts()

0.0     499976
1.0     499976
26.0    499976
27.0    499976
28.0    499976
29.0    499976
30.0    499976
31.0    499976
32.0    499976
33.0    499976
34.0    499976
35.0    499976
36.0    499976
37.0    499976
38.0    499976
39.0    499976
40.0    499976
41.0    499976
42.0    499976
43.0    499976
44.0    499976
45.0    499976
46.0    499976
25.0    499976
24.0    499976
23.0    499976
11.0    499976
2.0     499976
3.0     499976
4.0     499976
5.0     499976
6.0     499976
7.0     499976
8.0     499976
9.0     499976
10.0    499976
12.0    499976
22.0    499976
13.0    499976
14.0    499976
15.0    499976
16.0    499976
17.0    499976
18.0    499976
19.0    499976
20.0    499976
21.0    499976
47.0    499976
Name: advertiserNumber, dtype: int64